name: Test Template Diff

on:
  pull_request:
    paths:
      - '.harness/templates/**'

jobs:
  test-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Add explicit permissions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for diffs

      - name: Run Template Diff
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Use the automatic token
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        id: diff 