name: Test Template Diff

on:
  pull_request:
    paths:
      - '.harness/templates/**'

jobs:
  test-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout PR head

      - name: Run Template Diff
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        id: diff 